export const homeObj1 = {
  id: "services",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topline: "Full Service Repair and Maintenance ",
  headline: "From oil changes to full engine replacements, we can take care of all your car needs",
  description: "For more information please contact us",
  buttonLabel: "Contact Us",
  imgStart: false,
  img: require("../../img/engine1.jpg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObj2 = {
  id: "location",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topline: "Conviently Located",
  headline: "We are located 1 mile off Interstate 35 and Slaughter Ln.",
  description: "To view our location on google maps, click below",
  buttonLabel: "Google Maps",
  imgStart: true,
  img: require("../../img/location.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObj3 = {
  id: "contact",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topline: "Full Service Repair and Maintenance ",
  headline: "This is the headline it can be as long as you want it",
  description: "This is the description section",
  buttonLabel: "This is button",
  imgStart: false,
  img: require("../../img/location.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObj4 = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topline: "Full Service Repair and Maintenance ",
  headline: "This is the headline it can be as long as you want it",
  description: "This is the description section",
  buttonLabel: "This is button",
  imgStart: true,
  img: require("../../img/car1.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};
